[2024-06-25T11:51:06.873+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-25T11:51:06.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.skip_run scheduled__2024-06-25T11:48:00+00:00 [queued]>
[2024-06-25T11:51:06.932+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.skip_run scheduled__2024-06-25T11:48:00+00:00 [queued]>
[2024-06-25T11:51:06.933+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 6
[2024-06-25T11:51:06.954+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): skip_run> on 2024-06-25 11:48:00+00:00
[2024-06-25T11:51:06.962+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=924) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-25T11:51:06.963+0000] {standard_task_runner.py:63} INFO - Started process 925 to run task
[2024-06-25T11:51:06.964+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'skip_run', 'scheduled__2024-06-25T11:48:00+00:00', '--job-id', '3817', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmp777kkrsw']
[2024-06-25T11:51:06.965+0000] {standard_task_runner.py:91} INFO - Job 3817: Subtask skip_run
[2024-06-25T11:51:07.025+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.skip_run scheduled__2024-06-25T11:48:00+00:00 [running]> on host ced2311e92d2
[2024-06-25T11:51:07.152+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='skip_run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-25T11:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-25T11:48:00+00:00'
[2024-06-25T11:51:07.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-25T11:51:07.514+0000] {helper_functions.py:191} INFO - []
[2024-06-25T11:51:07.514+0000] {helper_functions.py:201} INFO - []
[2024-06-25T11:51:07.515+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-25T11:51:07.515+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helper_functions.py", line 202, in alert_notif_skipped_api
    encrypted_airflow = fernet.encrypt(airflow_api_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cryptography/fernet.py", line 52, in encrypt
    return self.encrypt_at_time(data, int(time.time()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cryptography/fernet.py", line 56, in encrypt_at_time
    return self._encrypt_from_parts(data, current_time, iv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cryptography/fernet.py", line 61, in _encrypt_from_parts
    utils._check_bytes("data", data)
  File "/home/airflow/.local/lib/python3.12/site-packages/cryptography/utils.py", line 31, in _check_bytes
    raise TypeError(f"{name} must be bytes")
TypeError: data must be bytes
[2024-06-25T11:51:07.527+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=demo_dag_for_alerting_apis_final, task_id=skip_run, run_id=scheduled__2024-06-25T11:48:00+00:00, execution_date=20240625T114800, start_date=20240625T115106, end_date=20240625T115107
[2024-06-25T11:51:07.546+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3817 for task skip_run (data must be bytes; 925)
[2024-06-25T11:51:07.581+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-25T11:51:07.606+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-25T11:51:07.607+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
