[2024-06-18T10:14:05.988+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T10:14:06.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alerting_skipped.start_run scheduled__2024-06-18T10:12:00+00:00 [queued]>
[2024-06-18T10:14:06.051+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alerting_skipped.start_run scheduled__2024-06-18T10:12:00+00:00 [queued]>
[2024-06-18T10:14:06.051+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-18T10:14:06.075+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): start_run> on 2024-06-18 10:12:00+00:00
[2024-06-18T10:14:06.083+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3568) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T10:14:06.085+0000] {standard_task_runner.py:63} INFO - Started process 3570 to run task
[2024-06-18T10:14:06.085+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'alerting_skipped', 'start_run', 'scheduled__2024-06-18T10:12:00+00:00', '--job-id', '548', '--raw', '--subdir', 'DAGS_FOLDER/alerting_skipped.py', '--cfg-path', '/tmp/tmptah48qcx']
[2024-06-18T10:14:06.087+0000] {standard_task_runner.py:91} INFO - Job 548: Subtask start_run
[2024-06-18T10:14:06.150+0000] {task_command.py:426} INFO - Running <TaskInstance: alerting_skipped.start_run scheduled__2024-06-18T10:12:00+00:00 [running]> on host fa5c5d972e05
[2024-06-18T10:14:06.293+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alerting_skipped' AIRFLOW_CTX_TASK_ID='start_run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T10:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T10:12:00+00:00'
[2024-06-18T10:14:06.294+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T10:14:06.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T10:14:06.327+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helper_functions.py", line 63, in start_run
    with open(alert_file_path, 'a') as alert_file:
              ^^^^^^^^^^^^^^^
NameError: name 'alert_file_path' is not defined
[2024-06-18T10:14:06.357+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=alerting_skipped, task_id=start_run, run_id=scheduled__2024-06-18T10:12:00+00:00, execution_date=20240618T101200, start_date=20240618T101406, end_date=20240618T101406
[2024-06-18T10:14:06.384+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 548 for task start_run (name 'alert_file_path' is not defined; 3570)
[2024-06-18T10:14:06.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-18T10:14:06.478+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-18T10:14:06.481+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
