[2024-06-28T10:09:05.558+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:09:05.589+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:08:00+00:00 [queued]>
[2024-06-28T10:09:05.602+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:08:00+00:00 [queued]>
[2024-06-28T10:09:05.603+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-28T10:09:05.628+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-28 10:08:00+00:00
[2024-06-28T10:09:05.636+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:09:05.638+0000] {standard_task_runner.py:63} INFO - Started process 106 to run task
[2024-06-28T10:09:05.637+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'check_data_in_stream', 'scheduled__2024-06-28T10:08:00+00:00', '--job-id', '4950', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmp8qa2v_3r']
[2024-06-28T10:09:05.639+0000] {standard_task_runner.py:91} INFO - Job 4950: Subtask check_data_in_stream
[2024-06-28T10:09:05.699+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:08:00+00:00 [running]> on host 2552e7b36400
[2024-06-28T10:09:05.802+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T10:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T10:08:00+00:00'
[2024-06-28T10:09:05.803+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:09:05.819+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-28T10:09:05.819+0000] {python.py:237} INFO - Done. Returned value was: skipped_due_to_data_unavailability
[2024-06-28T10:09:05.819+0000] {branch.py:36} INFO - Branch into skipped_due_to_data_unavailability
[2024-06-28T10:09:05.820+0000] {skipmixin.py:178} INFO - Following branch skipped_due_to_data_unavailability
[2024-06-28T10:09:05.836+0000] {skipmixin.py:246} INFO - Skipping tasks [('insert_new_record_into_audit_table', -1)]
[2024-06-28T10:09:05.862+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:09:05.885+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_apis_final, task_id=check_data_in_stream, run_id=scheduled__2024-06-28T10:08:00+00:00, execution_date=20240628T100800, start_date=20240628T100905, end_date=20240628T100905
[2024-06-28T10:09:05.932+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T10:09:05.968+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:09:05.973+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
