[2024-06-17T15:04:31.853+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: alerting_skipped.check_status manual__2024-06-17T15:01:24.316096+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
