[2024-06-20T18:50:51.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T18:50:51.268+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alerting_all_dags_using_apis.get_all_dag_ids_last_limit_run_ids manual__2024-06-20T18:50:47.944388+00:00 [queued]>
[2024-06-20T18:50:51.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alerting_all_dags_using_apis.get_all_dag_ids_last_limit_run_ids manual__2024-06-20T18:50:47.944388+00:00 [queued]>
[2024-06-20T18:50:51.280+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T18:50:51.297+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_all_dag_ids_last_limit_run_ids> on 2024-06-20 18:50:47.944388+00:00
[2024-06-20T18:50:51.302+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2019) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T18:50:51.303+0000] {standard_task_runner.py:63} INFO - Started process 2020 to run task
[2024-06-20T18:50:51.303+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'alerting_all_dags_using_apis', 'get_all_dag_ids_last_limit_run_ids', 'manual__2024-06-20T18:50:47.944388+00:00', '--job-id', '2629', '--raw', '--subdir', 'DAGS_FOLDER/alerting_all_dags_using_apis.py', '--cfg-path', '/tmp/tmpgr7xy_t4']
[2024-06-20T18:50:51.304+0000] {standard_task_runner.py:91} INFO - Job 2629: Subtask get_all_dag_ids_last_limit_run_ids
[2024-06-20T18:50:51.348+0000] {task_command.py:426} INFO - Running <TaskInstance: alerting_all_dags_using_apis.get_all_dag_ids_last_limit_run_ids manual__2024-06-20T18:50:47.944388+00:00 [running]> on host e66744caf823
[2024-06-20T18:50:51.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alerting_all_dags_using_apis' AIRFLOW_CTX_TASK_ID='get_all_dag_ids_last_limit_run_ids' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T18:50:47.944388+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T18:50:47.944388+00:00'
[2024-06-20T18:50:51.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T18:50:51.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T18:50:51.476+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helper_functions.py", line 182, in get_all_dag_ids_last_limit_run_ids
    for dag_id in active_dag_ids:
                  ^^^^^^^^^^^^^^
NameError: name 'active_dag_ids' is not defined
[2024-06-20T18:50:51.496+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=alerting_all_dags_using_apis, task_id=get_all_dag_ids_last_limit_run_ids, run_id=manual__2024-06-20T18:50:47.944388+00:00, execution_date=20240620T185047, start_date=20240620T185051, end_date=20240620T185051
[2024-06-20T18:50:51.508+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2629 for task get_all_dag_ids_last_limit_run_ids (name 'active_dag_ids' is not defined; 2020)
[2024-06-20T18:50:51.516+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T18:50:51.543+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T18:50:51.545+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
