[2024-06-18T05:27:54.996+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-18T05:27:55.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alerting_skipped.check_status manual__2024-06-18T05:27:53.790984+00:00 [queued]>
[2024-06-18T05:27:55.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alerting_skipped.check_status manual__2024-06-18T05:27:53.790984+00:00 [queued]>
[2024-06-18T05:27:55.031+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-18T05:27:55.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): check_status> on 2024-06-18 05:27:53.790984+00:00
[2024-06-18T05:27:55.054+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-18T05:27:55.055+0000] {standard_task_runner.py:63} INFO - Started process 278 to run task
[2024-06-18T05:27:55.056+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'alerting_skipped', 'check_status', 'manual__2024-06-18T05:27:53.790984+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/alerting_skipped.py', '--cfg-path', '/tmp/tmpk1_6my4y']
[2024-06-18T05:27:55.057+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask check_status
[2024-06-18T05:27:55.097+0000] {task_command.py:426} INFO - Running <TaskInstance: alerting_skipped.check_status manual__2024-06-18T05:27:53.790984+00:00 [running]> on host fa5c5d972e05
[2024-06-18T05:27:55.190+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alerting_skipped' AIRFLOW_CTX_TASK_ID='check_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T05:27:53.790984+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-18T05:27:53.790984+00:00'
[2024-06-18T05:27:55.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-18T05:27:55.207+0000] {alerting_skipped.py:67} ERROR - Error querying DAG run status: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/dags/alerting_skipped/dagRuns?limit=3&order_by=-execution_date (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x70e7bb33f5c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-06-18T05:27:55.208+0000] {python.py:237} INFO - Done. Returned value was: False
[2024-06-18T05:27:55.208+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-18T05:27:55.229+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=alerting_skipped, task_id=check_status, run_id=manual__2024-06-18T05:27:53.790984+00:00, execution_date=20240618T052753, start_date=20240618T052755, end_date=20240618T052755
[2024-06-18T05:27:55.269+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-18T05:27:55.308+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-18T05:27:55.310+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
