[2024-06-26T08:32:07.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-26T08:32:07.343+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-26T08:30:00+00:00 [queued]>
[2024-06-26T08:32:07.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-26T08:30:00+00:00 [queued]>
[2024-06-26T08:32:07.356+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-26T08:32:07.377+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-26 08:30:00+00:00
[2024-06-26T08:32:07.385+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4890) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-26T08:32:07.387+0000] {standard_task_runner.py:63} INFO - Started process 4894 to run task
[2024-06-26T08:32:07.387+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'check_data_in_stream', 'scheduled__2024-06-26T08:30:00+00:00', '--job-id', '4178', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmpqqcoyj8q']
[2024-06-26T08:32:07.388+0000] {standard_task_runner.py:91} INFO - Job 4178: Subtask check_data_in_stream
[2024-06-26T08:32:07.443+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-26T08:30:00+00:00 [running]> on host ced2311e92d2
[2024-06-26T08:32:07.561+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-26T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-26T08:30:00+00:00'
[2024-06-26T08:32:07.562+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-26T08:32:07.581+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-26T08:32:07.582+0000] {python.py:237} INFO - Done. Returned value was: insert_new_record_into_audit_table
[2024-06-26T08:32:07.582+0000] {branch.py:36} INFO - Branch into insert_new_record_into_audit_table
[2024-06-26T08:32:07.582+0000] {skipmixin.py:178} INFO - Following branch insert_new_record_into_audit_table
[2024-06-26T08:32:07.610+0000] {skipmixin.py:246} INFO - Skipping tasks [('skipped_due_to_data_unavailability', -1)]
[2024-06-26T08:32:07.639+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-26T08:32:07.663+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_apis_final, task_id=check_data_in_stream, run_id=scheduled__2024-06-26T08:30:00+00:00, execution_date=20240626T083000, start_date=20240626T083207, end_date=20240626T083207
[2024-06-26T08:32:07.721+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-26T08:32:07.761+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-26T08:32:07.762+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
