[2024-06-28T10:02:04.675+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T10:02:04.722+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:01:00+00:00 [queued]>
[2024-06-28T10:02:04.741+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:01:00+00:00 [queued]>
[2024-06-28T10:02:04.742+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-28T10:02:04.764+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-28 10:01:00+00:00
[2024-06-28T10:02:04.771+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8571) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-28T10:02:04.772+0000] {standard_task_runner.py:63} INFO - Started process 8573 to run task
[2024-06-28T10:02:04.772+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'check_data_in_stream', 'scheduled__2024-06-28T10:01:00+00:00', '--job-id', '4907', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmp883xn_zd']
[2024-06-28T10:02:04.774+0000] {standard_task_runner.py:91} INFO - Job 4907: Subtask check_data_in_stream
[2024-06-28T10:02:04.834+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-28T10:01:00+00:00 [running]> on host eeacb89bcfc1
[2024-06-28T10:02:04.966+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T10:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-28T10:01:00+00:00'
[2024-06-28T10:02:04.967+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T10:02:04.988+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-28T10:02:04.989+0000] {python.py:237} INFO - Done. Returned value was: skipped_due_to_data_unavailability
[2024-06-28T10:02:04.990+0000] {branch.py:36} INFO - Branch into skipped_due_to_data_unavailability
[2024-06-28T10:02:04.990+0000] {skipmixin.py:178} INFO - Following branch skipped_due_to_data_unavailability
[2024-06-28T10:02:05.013+0000] {skipmixin.py:246} INFO - Skipping tasks [('insert_new_record_into_audit_table', -1)]
[2024-06-28T10:02:05.040+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T10:02:05.059+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_apis_final, task_id=check_data_in_stream, run_id=scheduled__2024-06-28T10:01:00+00:00, execution_date=20240628T100100, start_date=20240628T100204, end_date=20240628T100205
[2024-06-28T10:02:05.106+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T10:02:05.174+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-28T10:02:05.184+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
