[2024-06-17T12:46:42.337+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T12:46:42.402+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: file_jsons_to_postgres.get_task_instances manual__2024-06-17T12:46:41.109844+00:00 [queued]>
[2024-06-17T12:46:42.415+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: file_jsons_to_postgres.get_task_instances manual__2024-06-17T12:46:41.109844+00:00 [queued]>
[2024-06-17T12:46:42.417+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-17T12:46:42.456+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_task_instances> on 2024-06-17 12:46:41.109844+00:00
[2024-06-17T12:46:42.463+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4769) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T12:46:42.464+0000] {standard_task_runner.py:63} INFO - Started process 4771 to run task
[2024-06-17T12:46:42.465+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'file_jsons_to_postgres', 'get_task_instances', 'manual__2024-06-17T12:46:41.109844+00:00', '--job-id', '339', '--raw', '--subdir', 'DAGS_FOLDER/file_jsons_to_postgres.py', '--cfg-path', '/tmp/tmpgkeag27n']
[2024-06-17T12:46:42.467+0000] {standard_task_runner.py:91} INFO - Job 339: Subtask get_task_instances
[2024-06-17T12:46:42.523+0000] {task_command.py:426} INFO - Running <TaskInstance: file_jsons_to_postgres.get_task_instances manual__2024-06-17T12:46:41.109844+00:00 [running]> on host 4d71c837c754
[2024-06-17T12:46:42.630+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='file_jsons_to_postgres' AIRFLOW_CTX_TASK_ID='get_task_instances' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T12:46:41.109844+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T12:46:41.109844+00:00'
[2024-06-17T12:46:42.631+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T12:46:42.649+0000] {file_jsons_to_postgres.py:136} INFO - Attempting to fetch task instances from: http://localhost:8080/api/v1/dags/file_jsons_to_postgres/tasks/insert_json
[2024-06-17T12:46:42.655+0000] {file_jsons_to_postgres.py:143} ERROR - Request failed: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/v1/dags/file_jsons_to_postgres/tasks/insert_json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7176663bdfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2024-06-17T12:46:42.656+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-17T12:46:42.657+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T12:46:42.671+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=file_jsons_to_postgres, task_id=get_task_instances, run_id=manual__2024-06-17T12:46:41.109844+00:00, execution_date=20240617T124641, start_date=20240617T124642, end_date=20240617T124642
[2024-06-17T12:46:42.720+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-17T12:46:42.738+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-17T12:46:42.740+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
