[2024-06-20T07:48:05.515+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:48:05.535+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_data_in_stream scheduled__2024-06-20T07:47:00+00:00 [queued]>
[2024-06-20T07:48:05.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_final_1.check_data_in_stream scheduled__2024-06-20T07:47:00+00:00 [queued]>
[2024-06-20T07:48:05.543+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T07:48:05.556+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-20 07:47:00+00:00
[2024-06-20T07:48:05.560+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1945) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-20T07:48:05.561+0000] {standard_task_runner.py:63} INFO - Started process 1946 to run task
[2024-06-20T07:48:05.562+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_final_1', 'check_data_in_stream', 'scheduled__2024-06-20T07:47:00+00:00', '--job-id', '1992', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting.py', '--cfg-path', '/tmp/tmpt_i3z2x6']
[2024-06-20T07:48:05.563+0000] {standard_task_runner.py:91} INFO - Job 1992: Subtask check_data_in_stream
[2024-06-20T07:48:05.599+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_final_1.check_data_in_stream scheduled__2024-06-20T07:47:00+00:00 [running]> on host e66744caf823
[2024-06-20T07:48:05.679+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_final_1' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:47:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-20T07:47:00+00:00'
[2024-06-20T07:48:05.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:48:05.691+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-20T07:48:05.697+0000] {python.py:237} INFO - Done. Returned value was: skipped_due_to_data_unavailability
[2024-06-20T07:48:05.697+0000] {branch.py:36} INFO - Branch into skipped_due_to_data_unavailability
[2024-06-20T07:48:05.697+0000] {skipmixin.py:178} INFO - Following branch skipped_due_to_data_unavailability
[2024-06-20T07:48:05.711+0000] {skipmixin.py:246} INFO - Skipping tasks [('insert_new_record_into_audit_table', -1)]
[2024-06-20T07:48:05.734+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:48:05.752+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_final_1, task_id=check_data_in_stream, run_id=scheduled__2024-06-20T07:47:00+00:00, execution_date=20240620T074700, start_date=20240620T074805, end_date=20240620T074805
[2024-06-20T07:48:05.775+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T07:48:05.807+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:48:05.811+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
