[2024-06-19T18:39:05.078+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T18:39:05.116+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-19T18:38:00+00:00 [queued]>
[2024-06-19T18:39:05.129+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-19T18:38:00+00:00 [queued]>
[2024-06-19T18:39:05.130+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-19T18:39:05.152+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_data_in_stream> on 2024-06-19 18:38:00+00:00
[2024-06-19T18:39:05.159+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1549) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T18:39:05.160+0000] {standard_task_runner.py:63} INFO - Started process 1551 to run task
[2024-06-19T18:39:05.161+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'demo_dag_for_alerting_apis_final', 'check_data_in_stream', 'scheduled__2024-06-19T18:38:00+00:00', '--job-id', '1764', '--raw', '--subdir', 'DAGS_FOLDER/demo_dag_for_alerting_apis.py', '--cfg-path', '/tmp/tmp8gsl29n6']
[2024-06-19T18:39:05.162+0000] {standard_task_runner.py:91} INFO - Job 1764: Subtask check_data_in_stream
[2024-06-19T18:39:05.217+0000] {task_command.py:426} INFO - Running <TaskInstance: demo_dag_for_alerting_apis_final.check_data_in_stream scheduled__2024-06-19T18:38:00+00:00 [running]> on host e66744caf823
[2024-06-19T18:39:05.334+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='demo_dag_for_alerting_apis_final' AIRFLOW_CTX_TASK_ID='check_data_in_stream' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T18:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T18:38:00+00:00'
[2024-06-19T18:39:05.335+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T18:39:05.353+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-06-19T18:39:05.354+0000] {python.py:237} INFO - Done. Returned value was: skipped_due_to_data_unavailability
[2024-06-19T18:39:05.354+0000] {branch.py:36} INFO - Branch into skipped_due_to_data_unavailability
[2024-06-19T18:39:05.354+0000] {skipmixin.py:178} INFO - Following branch skipped_due_to_data_unavailability
[2024-06-19T18:39:05.374+0000] {skipmixin.py:246} INFO - Skipping tasks [('insert_new_record_into_audit_table', -1)]
[2024-06-19T18:39:05.402+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T18:39:05.425+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=demo_dag_for_alerting_apis_final, task_id=check_data_in_stream, run_id=scheduled__2024-06-19T18:38:00+00:00, execution_date=20240619T183800, start_date=20240619T183905, end_date=20240619T183905
[2024-06-19T18:39:05.455+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T18:39:05.492+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T18:39:05.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
