[2024-06-11T17:55:13.004+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T17:55:13.031+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_txt_to_postgres_dag.read_and_process_json_task manual__2024-06-11T17:50:05.964753+00:00 [queued]>
[2024-06-11T17:55:13.039+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_txt_to_postgres_dag.read_and_process_json_task manual__2024-06-11T17:50:05.964753+00:00 [queued]>
[2024-06-11T17:55:13.040+0000] {taskinstance.py:2306} INFO - Starting attempt 6 of 6
[2024-06-11T17:55:13.054+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_and_process_json_task> on 2024-06-11 17:50:05.964753+00:00
[2024-06-11T17:55:13.061+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=874) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T17:55:13.062+0000] {standard_task_runner.py:63} INFO - Started process 875 to run task
[2024-06-11T17:55:13.063+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_txt_to_postgres_dag', 'read_and_process_json_task', 'manual__2024-06-11T17:50:05.964753+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/process_txt_to_postgres_dag.py', '--cfg-path', '/tmp/tmpn1n5_2p6']
[2024-06-11T17:55:13.064+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask read_and_process_json_task
[2024-06-11T17:55:13.107+0000] {task_command.py:426} INFO - Running <TaskInstance: process_txt_to_postgres_dag.read_and_process_json_task manual__2024-06-11T17:50:05.964753+00:00 [running]> on host 0fddd2b8b561
[2024-06-11T17:55:13.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_txt_to_postgres_dag' AIRFLOW_CTX_TASK_ID='read_and_process_json_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T17:50:05.964753+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T17:50:05.964753+00:00'
[2024-06-11T17:55:13.198+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T17:55:13.211+0000] {process_txt_to_postgres_dag.py:11} INFO - Reading file from path: /home/nikhilnamburi/Desktop/python/***/sources/dataForAirflow.txt
[2024-06-11T17:55:13.211+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T17:55:13.212+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/process_txt_to_postgres_dag.py", line 14, in read_and_process_json
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/nikhilnamburi/Desktop/python/airflow/sources/dataForAirflow.txt'
[2024-06-11T17:55:13.219+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=process_txt_to_postgres_dag, task_id=read_and_process_json_task, run_id=manual__2024-06-11T17:50:05.964753+00:00, execution_date=20240611T175005, start_date=20240611T175513, end_date=20240611T175513
[2024-06-11T17:55:13.229+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task read_and_process_json_task ([Errno 2] No such file or directory: '/home/nikhilnamburi/Desktop/python/airflow/sources/dataForAirflow.txt'; 875)
[2024-06-11T17:55:13.236+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T17:55:13.257+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T17:55:13.260+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
